openapi: 3.1.1

info:
  title: Stock management API
  version: '1.0.0'
  description: |
    This API is designed to manage products available quantity, use it or restock.

paths:
  /products:
    get:
      operationId: list
      summary: Get all available product references.
      tags:
        - products
      responses:
        200:
          description: Requested product reference list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductReference'
  /products/{productReference}:
    description: Product management by its reference
    get:
      operationId: get
      summary: Get a products by its reference
      tags:
        - products
      parameters:
        - name: productReference
          description: Reference of the requested products
          in: path
          schema:
            type: string
          required: true
      responses:
        200:
          description: The related product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDetails'
        404:
          description: No product corresponding to given reference
  /products/{productReference}/restock:
    patch:
      operationId: restock
      summary: Add additionnal quantity to a product stock
      tags:
        - products
      parameters:
        - name: productReference
          description: Reference of the requested products
          in: path
          schema:
            type: string
          required: true
        - name: quantity
          description: Quantity to add to the current stock
          in: query
          schema:
            type: integer
            format: int32
            minimum: 1
          required: true
      responses:
        200:
          description: The submitted composition
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDetails'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestReason'
        404:
          description: No product corresponding to given reference
  /products/{productReference}/use:
    patch:
      operationId: use
      summary: Consume a quantity of the available product quantity
      tags:
        - products
      parameters:
        - name: productReference
          description: Reference of the requested products
          in: path
          schema:
            type: string
          required: true
        - name: quantity
          description: Quantity to consume from the current stock
          in: query
          schema:
            type: integer
            format: int32
            minimum: 1
          required: true
      responses:
        200:
          description: Available perimeters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDetails'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestReason'
        404:
          description: No product corresponding to given reference
        422:
          description: Insufficient stock for requested operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestReason'
components:
  schemas:
    ProductReference:
      type: object
      properties:
        reference:
          type: string
          description: reference of the product
        description:
          type: string
          description: description of the product
    ProductDetails:
      type: object
      properties:
        reference:
          type: string
          description: reference of the product
        description:
          type: string
          description: description of the product
        stock:
          type: number
          format: int32
          description: available quantity of the product
        updatedAt:
          type: string
          format: date-time
          description: last update of the product stock
    BadRequestReason:
      type: object
      properties:
        reason:
          type: string
          description: reason of a bad request response

tags:
  - name: products
    description: 'Endpoint about product resources'
